"""empty message

Revision ID: 2ff7ae635a11
Revises: 161e11ca7458
Create Date: 2023-08-23 01:43:30.807451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff7ae635a11'
down_revision = '161e11ca7458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritesplanets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favoritesplanets_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['planets_id'], ['id'])
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritesplanets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favoritesplanets_planet_id_fkey', 'planets', ['planet_id'], ['id'])
        batch_op.drop_column('planets_id')

    # ### end Alembic commands ###
